application: image-host
version: 1
runtime: python
api_version: 1

handlers:
- url: /imagehost/assets
  static_dir: appengineimagehost/assets
  
- url: /imagehost/i/(img|thumb).*
  script: appengineimagehost/frontend.py

- url: /imagehost/.*
  script: appengineimagehost/backend.py
  login: admin